# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Palbase < Formula
  desc "Palbase CLI — develop, test, and deploy backend projects"
  homepage "https://palbase.studio"
  version "0.2.8"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/palgroup/palbase-cli/releases/download/v0.2.8/palbase_darwin_amd64.tar.gz"
      sha256 "e10a9d4f1f553ab916ca95411e58772ba1dfeb233a56362d02a85da76173a025"

      define_method(:install) do
        bin.install "palbase"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/palgroup/palbase-cli/releases/download/v0.2.8/palbase_darwin_arm64.tar.gz"
      sha256 "d40ede7c3e988e66afc8b3a948be6a2d935f5f0bb99cbed33046dc4c5ea8a5b5"

      define_method(:install) do
        bin.install "palbase"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/palgroup/palbase-cli/releases/download/v0.2.8/palbase_linux_amd64.tar.gz"
      sha256 "b3e0d4ada74fa6991e00db7c98f65da954f5e29c5add23052cde45ab1a881209"
      define_method(:install) do
        bin.install "palbase"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/palgroup/palbase-cli/releases/download/v0.2.8/palbase_linux_arm64.tar.gz"
      sha256 "dfd2b1625295f30582974d767e9921726eabbee4b4d1a5d389fb9599faecf00c"
      define_method(:install) do
        bin.install "palbase"
      end
    end
  end

  test do
    system "#{bin}/palbase", "--version"
  end
end
