# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Palbase < Formula
  desc "Palbase CLI — develop, test, and deploy backend projects"
  homepage "https://palbase.studio"
  version "0.2.6"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/palgroup/palbase-cli/releases/download/v0.2.6/palbase_darwin_amd64.tar.gz"
      sha256 "8dab7a81f795be422394c1a084ff7bcee035f2c9699563fc1497f12baa7de3be"

      define_method(:install) do
        bin.install "palbase"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/palgroup/palbase-cli/releases/download/v0.2.6/palbase_darwin_arm64.tar.gz"
      sha256 "0e3de74a24c2428642f15040d5883dd53a10e5413b337f9e2102849e2d109246"

      define_method(:install) do
        bin.install "palbase"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/palgroup/palbase-cli/releases/download/v0.2.6/palbase_linux_amd64.tar.gz"
      sha256 "e40e0be2a53405d6939c392312560cd1dfc7fc18be10e4ee9726ec53623580ba"
      define_method(:install) do
        bin.install "palbase"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/palgroup/palbase-cli/releases/download/v0.2.6/palbase_linux_arm64.tar.gz"
      sha256 "bfc6e532f14748414947253bf85806d268cc709e48cae68559967bf4fb37ad63"
      define_method(:install) do
        bin.install "palbase"
      end
    end
  end

  test do
    system "#{bin}/palbase", "--version"
  end
end
