# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Palbase < Formula
  desc "Palbase CLI — develop, test, and deploy backend projects"
  homepage "https://palbase.studio"
  version "0.2.13"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/palgroup/palbase-cli/releases/download/v0.2.13/palbase_darwin_amd64.tar.gz"
      sha256 "c3e379f48e008e4bd253a0d361d04f00512e1e604ca1b4c9f3a1dd390aade601"

      define_method(:install) do
        bin.install "palbase"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/palgroup/palbase-cli/releases/download/v0.2.13/palbase_darwin_arm64.tar.gz"
      sha256 "30b31137ffabd04eb828bbb8432aaa1d8a5fd8a8b54cb88a2560253192b1e6a1"

      define_method(:install) do
        bin.install "palbase"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/palgroup/palbase-cli/releases/download/v0.2.13/palbase_linux_amd64.tar.gz"
      sha256 "64e4eec2c9cb8c23841b074a73b06f226f6a46e5724db28af2373cb25957d091"
      define_method(:install) do
        bin.install "palbase"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/palgroup/palbase-cli/releases/download/v0.2.13/palbase_linux_arm64.tar.gz"
      sha256 "714314e77e0666e9f02cdb2824c26bbc40591c56c0872bdd32c9fbd4101f43ad"
      define_method(:install) do
        bin.install "palbase"
      end
    end
  end

  test do
    system "#{bin}/palbase", "--version"
  end
end
